name: Set reviewer for v18
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "18.0"
  push:
    branches:
      - "18.0"

jobs:
  pr18:
    runs-on: ubuntu-latest

    #env:
    #  GH_TOKEN: ${{ github.token }}
    #  GH_TOKENS: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.PR18_APP_ID }}
        private-key: ${{ secrets.PR18_SECRET_KEY }}
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Install GitHub CLI
    #  run: |
    #    sudo apt update
    #    sudo apt install gh -y

    - name: Assign reviewer method 1
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        url: "https://github.com/scopen-coop/dolibarr/pull/8"
      run: |
        echo We are there
        echo gh pr edit "$url" --add-reviewer marc-dll
        gh pr edit "$url" --add-reviewer marc-dll
        echo gh pr edit "$url" --add-reviewer FHenry
        gh pr edit "$url" --add-reviewer FHenry
